In [1]:
import numpy as np

In [ ]:
lst = [1,2,3]

In [ ]:
lst

[1, 2, 3]

In [ ]:
v1 = np.array(lst)

In [ ]:
v1

array([1, 2, 3])

In [ ]:
v1.shape

(3,)

In [ ]:
lst1 = [[1,2,3],[4,5,6],[7,8,9]]
lst1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
v2 = np.array(lst1)

In [ ]:
v2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.linspace(1,10,8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [6]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.random.rand(2)

array([0.33752756, 0.69073948])

In [10]:
np.random.rand(5,5)

array([[0.83522321, 0.28595876, 0.29176868, 0.80607266, 0.79832436],
       [0.00485469, 0.28039545, 0.37737207, 0.67661749, 0.15227227],
       [0.00262736, 0.4873769 , 0.29366727, 0.02637201, 0.66144261],
       [0.4287873 , 0.31459482, 0.46718008, 0.37045635, 0.07468648],
       [0.5428555 , 0.51622611, 0.03537904, 0.49600428, 0.44249726]])

In [24]:
np.random.randint(1,5)

3

In [29]:
np.shape

<function numpy.shape>

In [ ]:
arr.reshape(5,5)

In [32]:
import numpy as np

In [37]:
# Create an empty array of 20 0's and replace the 4th object with the number 5
a = np.zeros(20)
a[3]=5
a

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [38]:
# Create an array of 20 1's and store it as a variable named array_master. Copy the same array into another variable named 
# array_copy

In [39]:
array_master = np.ones(20)

array_copy = array_master.copy()

In [40]:
array_copy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [41]:
# Create an array containing 30 1's and broadcast all the one's to the value 100

In [42]:
array = np.ones(30)

array[:] = 100

array

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

In [44]:
array = np.zeros(30)

array[:] = 50

array

array([50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
       50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
       50., 50., 50., 50.])

In [47]:
array1 = np.ones(40)

array1[:] = 10.0

In [48]:
array1

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10.])

In [50]:
array1 = np.ones(20)

array1[:] = 20

array1

array([20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
       20., 20., 20., 20., 20., 20., 20.])

In [51]:
 Create an array of integers starting from 21 until 31 and name it as array1
Create an array of integers starting from 11 until 21 and name it array2
Calculate the difference between array1 and array2


In [53]:
array1 = np.arange(21,32)

array2 = np.arange(11,22)

array1 - array2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [54]:
a1 = np.arange(2,11,2)

a2 = np.arange(22,31,2)

np.stack((a1,a2))

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [55]:
a1 = np.arange(2,11,2)

a2 = np.arange(22,31,2)

In [56]:
a1

array([ 2,  4,  6,  8, 10])

In [57]:
np.column_stack((a1,a2))

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

In [59]:
A1 = np.arange(1,51,3)

A2 = np.arange(52,101,3)

np.stack((A1,A2))

array([[  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
         40,  43,  46,  49],
       [ 52,  55,  58,  61,  64,  67,  70,  73,  76,  79,  82,  85,  88,
         91,  94,  97, 100]])

In [60]:
np.column_stack((A1,A2))

array([[  1,  52],
       [  4,  55],
       [  7,  58],
       [ 10,  61],
       [ 13,  64],
       [ 16,  67],
       [ 19,  70],
       [ 22,  73],
       [ 25,  76],
       [ 28,  79],
       [ 31,  82],
       [ 34,  85],
       [ 37,  88],
       [ 40,  91],
       [ 43,  94],
       [ 46,  97],
       [ 49, 100]])

In [61]:
array_matrix = np.arange(30).reshape(5,6)

In [62]:
array_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [69]:
array_matrix[1,2]

8

In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [64]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
newarr = arr.reshape(4, 3)

In [66]:
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [70]:
array_matrix = np.arange(30).reshape(5,6)

In [71]:
array_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [72]:
array_matrix[2,3]

15

In [75]:
array_matrix[2:,1:]

array([[13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [79]:
array_matrix[2][3:]

array([15, 16, 17])

In [82]:
array_matrix[3]

array([18, 19, 20, 21, 22, 23])

In [93]:
array_matrix[3:4,3]

array([21])

In [94]:
array_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [97]:
array_matrix[4:5,4]

array([28])

In [107]:
array_matrix[[2,4][1]]

array([24, 25, 26, 27, 28, 29])

In [112]:
array_matrix[[1,3][0]]

array([ 6,  7,  8,  9, 10, 11])

In [116]:
array_matrix[[2,4][1]][2]

26

In [122]:
array_matrix[[2,4][1]]

array([24, 25, 26, 27, 28, 29])